# Generated by Django 4.2.7 on 2024-01-08 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Unique project name')),
                ('title', models.CharField(max_length=100, verbose_name='Project title')),
                ('description', models.TextField(verbose_name='Project description')),
                ('active_flag', models.BooleanField(default=True, verbose_name='Show project on the web')),
                ('beauty_shot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='beauty_shot', to='documents.photo', verbose_name='Main project picture')),
            ],
        ),
    ]
