# Generated by Django 4.2.7 on 2024-01-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_page_copy', models.TextField(verbose_name='Home page main text')),
                ('address_line1', models.CharField(max_length=60, verbose_name='Address (first line)')),
                ('address_line2', models.CharField(max_length=60, verbose_name='Address (second line)')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Public email address')),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Public phone number')),
                ('contact_us_emails', models.CharField(max_length=400, verbose_name='Contact us emails')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
