# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_image', models.ImageField(upload_to='home', verbose_name='Carousel Image')),
                ('caption', models.CharField(max_length=100, verbose_name='Image Caption')),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='home_page_copy',
            field=models.CharField(default='test', max_length=800, verbose_name='Home page main text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Service description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Service title'),
        ),
        migrations.AlterField(
            model_name='site',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Public email address'),
        ),
        migrations.AlterField(
            model_name='site',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Public phone number'),
        ),
    ]
