# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20151230_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_page_copy', models.TextField(verbose_name='Home page main text')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Public email address')),
                ('contact_phone', models.CharField(blank=True, max_length=15, verbose_name='Public phone number')),
            ],
        ),
        migrations.RenameModel(
            old_name='HomePage',
            new_name='HomePageImage',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
