# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20151231_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='main_category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='service',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tag_list',
        ),
        migrations.AlterField(
            model_name='project',
            name='active_flag',
            field=models.BooleanField(default=True, verbose_name='Show project on the web'),
        ),
        migrations.AlterField(
            model_name='project',
            name='beauty_shot',
            field=models.ImageField(upload_to=web.models.generate_foldername, verbose_name='Main project picture'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Unique project name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Project title'),
        ),
        migrations.AlterField(
            model_name='projectdescription',
            name='paragraph',
            field=models.TextField(verbose_name='Project description paragraph'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Project detail picture'),
        ),
    ]
