# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20151231_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='facebook_address',
            field=models.CharField(blank=True, max_length=40, verbose_name='Public Facebook page'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='linkedin_address',
            field=models.CharField(blank=True, max_length=40, verbose_name='Public Linked-In page'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='posted_hours',
            field=models.CharField(blank=True, max_length=60, verbose_name='Public posted hours'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='twitter_address',
            field=models.CharField(blank=True, max_length=40, verbose_name='Public Twitter address'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to=web.models.generate_detail_foldername, verbose_name='Project detail picture'),
        ),
    ]
