# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20151231_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='address_line1',
            field=models.CharField(default='test', max_length=40, verbose_name='Address (first line)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='address_line2',
            field=models.CharField(default='test', max_length=40, verbose_name='Address (second line)'),
            preserve_default=False,
        ),
    ]
