# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_aboutpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name_plural': 'About page'},
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='facebook_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Public Facebook page'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='linkedin_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Public Linked-In page'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='twitter_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Public Twitter address'),
        ),
    ]
