# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20160101_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(max_length=100, verbose_name='From')),
                ('from_phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('from_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message_text', models.TextField(verbose_name='Message')),
                ('message_date', models.DateTimeField(auto_now=True, verbose_name='Message date')),
            ],
        ),
    ]
