# Generated by Django 4.2.7 on 2024-03-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Category'),
        ),
        migrations.DeleteModel(
            name='PhotoTag',
        ),
    ]
