# Generated by Django 4.2.7 on 2024-01-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full name')),
                ('email', models.CharField(max_length=254, verbose_name='Email')),
                ('message_text', models.TextField(verbose_name='Message text')),
                ('message_date', models.DateTimeField(auto_now_add=True, verbose_name='Message date')),
            ],
        ),
    ]
