# Generated by Django 4.2.7 on 2024-03-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='title',
            field=models.CharField(default='foo', max_length=120, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
